---
- name: Ensure backup directory exists
  ansible.builtin.file:
    path: "{{ n8n_backup_dir }}"
    state: directory
    owner: "{{ n8n_user }}"
    group: "{{ n8n_group }}"
    mode: '0750'

- name: Copy database backup script
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      
      # Variables
      BACKUP_DIR="{{ n8n_backup_dir }}"
      DB_NAME="{{ n8n_db_name }}"
      DB_USER="{{ n8n_db_user }}"
      DB_PASS="{{ n8n_db_password }}"
      DB_HOST="{{ n8n_db_host }}"
      DATE=$(date +"%Y-%m-%d_%H-%M-%S")
      RETENTION_DAYS={{ n8n_backup_retention }}
      
      # Create backup file
      mysqldump -h ${DB_HOST} -u ${DB_USER} -p${DB_PASS} ${DB_NAME} > ${BACKUP_DIR}/n8n_${DATE}.sql
      
      # Compress backup
      gzip ${BACKUP_DIR}/n8n_${DATE}.sql
      
      # Remove old backups
      find ${BACKUP_DIR} -name "n8n_*.sql.gz" -type f -mtime +${RETENTION_DAYS} -delete
      
      # Export workflows as JSON (optional)
      if command -v jq &> /dev/null; then
        mkdir -p ${BACKUP_DIR}/workflows_${DATE}
        mysql -h ${DB_HOST} -u ${DB_USER} -p${DB_PASS} ${DB_NAME} -e "SELECT data FROM workflow_entity" -N | \
          while read -r data; do
            # Extract workflow name and ID from JSON data using jq
            if [ ! -z "$data" ]; then
              wf_id=$(echo $data | jq -r '.id')
              wf_name=$(echo $data | jq -r '.name' | tr ' ' '_')
              echo $data | jq '.' > ${BACKUP_DIR}/workflows_${DATE}/${wf_id}_${wf_name}.json
            fi
          done
        
        # Archive workflows directory
        tar -czf ${BACKUP_DIR}/n8n_workflows_${DATE}.tar.gz -C ${BACKUP_DIR} workflows_${DATE}
        
        # Remove temporary directory
        rm -rf ${BACKUP_DIR}/workflows_${DATE}
        
        # Remove old workflow backups
        find ${BACKUP_DIR} -name "n8n_workflows_*.tar.gz" -type f -mtime +${RETENTION_DAYS} -delete
      fi
      
      echo "Backup completed on $(date)"
    dest: /usr/local/bin/backup-n8n.sh
    owner: root
    group: root
    mode: '0755'

- name: Setup cron job for daily backup
  ansible.builtin.cron:
    name: "n8n database backup"
    hour: "3"
    minute: "30"
    job: "/usr/local/bin/backup-n8n.sh"
    user: "{{ n8n_user }}"
    state: present
