---
- name: Create n8n database
  mysql_db:
    name: "{{ n8n_database[0].db_name }}"
    state: present
    login_host: "{{ n8n_database[0].mysql_host }}"
    login_user: "{{ n8n_database[0].mysql_user }}"
    login_password: "{{ n8n_database[0].mysql_password }}"
  register: db_creation

- name: Grant privileges to n8n database
  mysql_user:
    name: "{{ n8n_database[0].mysql_user }}"
    password: "{{ n8n_database[0].mysql_password }}"
    host: "%"
    priv: "{{ n8n_database[0].db_name }}.*:ALL"
    state: present
    login_host: "{{ n8n_database[0].mysql_host }}"
    login_user: "{{ n8n_database[0].mysql_user }}"
    login_password: "{{ n8n_database[0].mysql_password }}"

- name: Create n8n environment file
  ansible.builtin.template:
    src: n8n.env.j2
    dest: "{{ n8n.data_dir }}/.env"
    owner: "{{ n8n.user }}"
    group: "{{ n8n.group }}"
    mode: '0640'
  notify: restart n8n

- name: Create n8n systemd service
  ansible.builtin.template:
    src: n8n.service.j2
    dest: /etc/systemd/system/n8n.service
    owner: root
    group: root
    mode: '0644'
  notify: restart n8n

- name: Configure UFW for n8n
  community.general.ufw:
    rule: allow
    port: "{{ n8n.port }}"
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Enable and start n8n service
  ansible.builtin.systemd:
    name: n8n
    state: started
    enabled: yes
    daemon_reload: yes
